// Generated by Wrangler
// After adding bindings to `wrangler.toml`, regenerate this interface via `npm run cf-typegen`
interface Env {
    VNP_URL: string;
    RETURN_URL: string;
    TMN_CODE: string;
    SECRET_KEY: string;
}
